In [4]:
import os
os.chdir("../../..")
print(os.getcwd())

/Users/titonka/FAIRIS


In [ ]:
import cv2
import numpy as np

In [5]:
def generate_apriltags(batch_size, tag_size=128, dictionary_type=cv2.aruco.DICT_APRILTAG_36h11, start_id=0):
    """
    Generate a batch of AprilTag images.

    Args:
        batch_size (int): Number of AprilTags to generate.
        tag_size (int): Size of each tag in pixels (default: 128).
        dictionary_type (int): ArUco dictionary type (default: DICT_APRILTAG_36h11).
        start_id (int): Starting ID for the tags (default: 0).

    Returns:
        list: List of generated AprilTag images as NumPy arrays.
    """
    dictionary = cv2.aruco.getPredefinedDictionary(dictionary_type)
    tags = []

    for tag_id in range(start_id, start_id + batch_size):
        # Generate the marker image
        tag_image = np.zeros((tag_size, tag_size), dtype=np.uint8)
        tag_image = cv2.aruco.generateImageMarker(dictionary, tag_id, tag_size, tag_image, 1)
        tags.append(tag_image)

        # Optional: Save to file
        cv2.imwrite(f"simulation/protos/WorldObjects/LandMarkTags/landmark_tag_{tag_id}.png", tag_image)
        print(f"Generated AprilTag ID {tag_id} and saved as apriltag_id{tag_id}.png")

    return tags

In [7]:
# Example usage: Generate 5 AprilTags of 128x128 pixels starting from ID 0
generate_apriltags(batch_size=8, tag_size=128)

Generated AprilTag ID 0 and saved as apriltag_id0.png
Generated AprilTag ID 1 and saved as apriltag_id1.png
Generated AprilTag ID 2 and saved as apriltag_id2.png
Generated AprilTag ID 3 and saved as apriltag_id3.png
Generated AprilTag ID 4 and saved as apriltag_id4.png
Generated AprilTag ID 5 and saved as apriltag_id5.png
Generated AprilTag ID 6 and saved as apriltag_id6.png
Generated AprilTag ID 7 and saved as apriltag_id7.png


[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(128, 128), dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(128, 128), dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(128, 128), dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], shape=(128, 128), dtype=uint8),
 array([[0, 0, 0, ..., 0